@jwtCookie1 = jwtToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNhaWxpbkBnbWFpbC5jb20iLCJfaWQiOiI2N2ZiY2I5NDU5NWM4YzcwODNlYjRlMzEiLCJpYXQiOjE3NDU5NDU5NTYsImV4cCI6MTc0NjAzMjM1Nn0.KUyllfX4B8LOW2j7sN7lZmGUO0vu1ijQ871phQpxjsQ
@jwtCookie2 = jwtToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNhaWxpbkBnbWFpbC5jb20iLCJfaWQiOiI2N2ZiY2I5NDU5NWM4YzcwODNlYjRlMzEiLCJpYXQiOjE3NDU5NDU5NTYsImV4cCI6MTc0NjAzMjM1Nn0.KUyllfX4B8LOW2j7sN7lZmGUO0vu1ijQ871phQpxjsQ
@id2 = "67ebb92cd6411ab0a86855ad"
@id1 = "67ebbbd7af6e27c442840a81"
POST http://localhost:5000/friends/request
Content-Type: application/json
Cookie: {{jwtCookie1}}

{
    "recipientId": "67ebbbd7af6e27c442840a81"
}

### 
PATCH  http://localhost:5000/friends/accept
Content-Type: application/json
Cookie: {{jwtCookie2}}

{
    "requesterId": "67ebb92cd6411ab0a86855ad"
}

### Get all friends
GET http://localhost:5000/friends
Content-Type: application/json
Cookie: {{jwtCookie1}}

### Get friend of a user with _id
GET http://localhost:5000/friends/67fbcb94595c8c7083eb4e31
Content-Type: application/json
Cookie: {{jwtCookie1}}