@jwtCookie1 = jwtToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNhaWxpbkBnbWFpbC5jb20iLCJfaWQiOiI2N2ZiY2I5NDU5NWM4YzcwODNlYjRlMzEiLCJpYXQiOjE3NDU5NDU5NTYsImV4cCI6MTc0NjAzMjM1Nn0.KUyllfX4B8LOW2j7sN7lZmGUO0vu1ijQ871phQpxjsQ
@jwtCookie2 = jwtToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFhbkBnbWFpbC5jb20iLCJfaWQiOiI2N2ViYmJkN2FmNmUyN2M0NDI4NDBhODEiLCJpYXQiOjE3NDM1MDIzMjksImV4cCI6MTc0MzU4ODcyOX0.LKyhkicJNl9e3DvW1lsC9lXqwpm-qxwJM9J9FpHToCc

######### USERS
GET http://localhost:5000/users/
Content-Type: application/json
Cookie: {{jwtCookie1}}

### GET profile
GET http://localhost:5000/users/profile
Content-Type: application/json
Cookie: {{jwtCookie1}}

### GET profile by ID
GET http://localhost:5000/users/profile/:id
Content-Type: application/json
Cookie: {{jwtCookie1}}

### PATCH user details
PATCH http://localhost:5000/users/update
Content-Type: application/json
Cookie: {{jwtCookie1}}

{
    "lastName": "Medusa"
}

### DELETE user profile                 
DELETE http://localhost:5000/users/delete-profile  
Content-Type: application/json
Cookie: {{ jwtCookie1 }}

### GET users with query.
GET http://localhost:5000/users/search?firstName=aan&lastName=
Content-Type: application/json    
Cookie: {{ jwtCookie1 }}